@extends("layouts.main")

@section("content")

    @includeWhen($user_guide->document_type instanceof \App\Models\DocumentType, 'partials.document-type-action-menu', ['document_type' => $user_guide->document_type])
    @include('partials.userguide-sidebar')

    <div class="app-userguide-content" id="app-userguide-content" data-userguide-id="{{ $user_guide->id }}" aria-hidden="false" role="presentation" aria-label="'{{ $user_guide->title }}' Content">
        <!-- Content will be generated by javascript -->
    </div>

@endsection